so=int(input("So ="))
sothunhat=((so//1000))
sothuhai=((so//100)%10)
sothuba=((so//10)%10)
sothutu=((so%10))
tong4so=(sothunhat+sothuhai+sothuba+sothutu)
print("Sothunhat",sothunhat)
print("Sothutu",sothutu)
print("Tong4so =",tong4so)